import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Caveat} from "next/font/google";
// Load the font
const excalifont = localFont({
  src: "../public/fonts/excalifont-Regular.woff2",
  display: "swap",
  variable: "--font-excalifont",
});
const virgil = localFont({
  src: "../public/fonts/virgil.woff2",
  display: "swap",
  variable: "--font-virgil",
});

const caveat = Caveat({
  variable : "--font-caveat",
  subsets : ["latin"],
  weight : "400"
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${caveat.variable} ${excalifont.variable} ${virgil.variable}  antialiased`}>{children}</body>
    </html>
  );
  // return (
  //   <html lang="en" >
  //     <body className={`${excaliFont.variable}` "antialiased"}>{children}</body>
  //   </html>
  // );

}
